const texts = {
  title: 'Профиль',
  settings: 'Настройки профиля',
  addAvatar: 'Добавьте аватар',
  changeAvatar: 'Изменить аватар',
  profileAvatar: 'Аватар профиля',
  firstNameTitle: 'Имя',
  firstNamePlaceholder: 'Ярополк',
  lastNameTitle: 'Фамилия',
  lastNamePlaceholder: 'Иванов',
  emailTitle: 'Email',
  emailPlaceholder: 'ivanov@yandex.ru',
  phoneTitle: 'Номер телефона',
  phonePlaceholder: '+7 (999) 888 77–66',
  chagePasswordTitle: 'Смена пароля',
  passwordTitle: 'Пароль',
  passwordPlaceholder: '********',
  newPasswordTitle: 'Новый пароль',
  repeatNewPasswordTitle: 'Повторите пароль',
  logout: 'Выйти из аккаунта',
  saveChanges: 'Сохранить изменения',
  loading: 'Загрузка...',
  pleaseSelectImageFile: 'Пожалуйста, выберите файл изображения',
  imageSizeShouldBeLessThan: 'Размер изображения должен быть не более 1 МБ',
  avatarUpdatedSuccessfully: 'Аватар успешно обновлен',
  failedUpdateAvatar: 'Не удалось обновить аватар',
  errorProcessingAvatar: 'Ошибка при обработке аватара',
  profileUpdatedSuccessfully: 'Профиль успешно обновлен',
  failedUpdateProfile: 'Не удалось обновить профиль',
  firstNameMinLength: 'Имя должно содержать минимум 2 буквы',
  firstNameMaxLength: 'Имя не должно превышать 30 символов',
  lastNameMinLength: 'Фамилия должна содержать минимум 2 буквы',
  lastNameMaxLength: 'Фамилия не должна превышать 30 символов',
  wrongEmail: 'Некорректный email',
  wrongPhoneNumber: 'Некорректный номер телефона',
  passwordMinLength: 'Пароль должен содержать минимум 8 символов',
  passwordsNotMatch: 'Пароли не совпадают',
  deleteAvatar: 'Удалить аватар',
  avatarDeletedSuccessfully: 'Аватар успешно удален',
  failedDeleteAvatar: 'Не удалось удалить аватар',
};

export default texts;
