name: Lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies ⚡
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies 🔧
        shell: bash
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run prettier 🧹
        run: npm run check

      - name: Run linter 📖
        run: npm run lint
